version: '3.8'

volumes:
  pg_data:
  redis-data:
  rabbitmq_data:

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: doglifedb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5499:5432"
    networks:
      - dogliveebot_network

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6399:6379"
    volumes:
      - redis-data:/data
    networks:
      - dogliveebot_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - dogliveebot_network

networks:
  dogliveebot_network: